tasks:
  - init: |
      sleep 120
      if test ! -e /workspace/hello; then
        printf '%s/%s' "$(date)" "$GITPOD_INSTANCE_ID" > /workspace/hello
      fi
# 3812

# 15271

# 29503

# 16377

# 5875
